name: Test actions crypto
on: 
    schedule:
        - cron: '* * * * *'
    push:
        branches: master

jobs:
    build:
  
      runs-on: ubuntu-latest
  
      steps:
      - uses: shinhwagk/release-notifier@master
        env:
          owner: "ceph"
          repo: "ceph"
          offset: 1111
