name: Test actions crypto
on: 
    schedule:
        - cron: '* * * * *'
    push:
        branches: master

jobs:
    build:
  
      runs-on: ubuntu-latest
  
      steps:
      - uses: shinhwagk/monitoring_document@master
        env:
          owner: "kubernetes"
          repo: "website"
          offset_hours: 1
          prefix: "content/en"
          incoming_webhooks: ${{ secrets.incoming_webhooks }}
