name: Test actions crypto
on: [push]

jobs:
    build:
  
      runs-on: ubuntu-latest
  
      steps:
      - uses: shinhwagk/monitoring_document@master
        env:
          owner: "kubernetes"
          repo: "website"
          offset_hours: 1
          prefix: "content/en"
          incoming_webhooks: ${{ secrets.incoming_webhooks }}